version: "3.9"

services:
  url-shortener:
    build: .
    container_name: url-shortener-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shortener
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
